#!/usr/bin/env bash
# codelattice-mcp.sh — Development MCP startup wrapper for CodeLattice contributors.
#
# Usage: bash scripts/codelattice-mcp.sh [--help|--version|--self-test]
#
# This checkout-local wrapper is intended for contributor/debug sessions. Daily
# AI client usage should point at the promoted stable wrapper generated by
# scripts/promote-to-local-tool.sh:
#
#   <install-dir>/codelattice-mcp.sh
#
# Environment variables:
#   CODELATTICE_ROOT       Override CodeLattice source root (default: auto-detect)
#   CODELATTICE_MCP_BIN    Use a pre-built binary instead of auto-detection
#   CODELATTICE_LOG_LEVEL  Log verbosity (reserved; server does not read this yet)
#
# Binary selection order:
#   1. CODELATTICE_MCP_BIN if set and executable
#   2. target/release/codelattice if exists
#   3. target/debug/codelattice if exists
#   4. target/release/gitnexus-rust-core-cli if exists (compat)
#   5. target/debug/gitnexus-rust-core-cli if exists (compat)
#   6. cargo run --features tree-sitter-cangjie,tree-sitter-arkts,tree-sitter-typescript -p gitnexus-rust-core-cli --bin codelattice -- mcp
#
# The MCP server speaks newline-delimited JSON-RPC over stdio.
# Logging goes to stderr only — stdout is pure JSON-RPC.

set -euo pipefail

# --- Auto-detect root from script location ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CODELATTICE_ROOT="${CODELATTICE_ROOT:-$DEFAULT_ROOT}"
CODELATTICE_MCP_BIN="${CODELATTICE_MCP_BIN:-}"
CODELATTICE_LOG_LEVEL="${CODELATTICE_LOG_LEVEL:-}"

# --- Helper: get profile info from binary via MCP initialize ---
# Sets _PROFILE_VERSION, _PROFILE_CANGJIE, _PROFILE_ARKTS, _PROFILE_TYPESCRIPT, _PROFILE_TOOLS
_get_profile() {
    local bin="$1"
    local init_resp
    init_resp=$(echo '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"profile","version":"1.0"}}}' | "$bin" mcp 2>/dev/null | head -1)
    _PROFILE_VERSION=$(echo "$init_resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo']['version'])" 2>/dev/null || echo "unknown")
    _PROFILE_CANGJIE=$(echo "$init_resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo'].get('cangjieSupport','unknown'))" 2>/dev/null || echo "unknown")
    _PROFILE_ARKTS=$(echo "$init_resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo'].get('arktsSupport','unknown'))" 2>/dev/null || echo "unknown")
    _PROFILE_TYPESCRIPT=$(echo "$init_resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo'].get('typescriptSupport','unknown'))" 2>/dev/null || echo "unknown")
    _PROFILE_TOOLS=$(echo "$init_resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo'].get('toolCount','unknown'))" 2>/dev/null || echo "unknown")
}

# --- Helper: select binary with profile validation ---
_select_binary() {
    local candidates=()

    # 1. Explicit override
    if [[ -n "$CODELATTICE_MCP_BIN" ]]; then
        if [[ ! -x "$CODELATTICE_MCP_BIN" ]]; then
            echo "ERROR: CODELATTICE_MCP_BIN not executable: $CODELATTICE_MCP_BIN" >&2
            exit 1
        fi
        SELECTED_BIN="$CODELATTICE_MCP_BIN"
        SELECTED_SOURCE="CODELATTICE_MCP_BIN"
        return
    fi

    # 2. Release binary
    if [[ -x "$CODELATTICE_ROOT/target/release/codelattice" ]]; then
        candidates+=("$CODELATTICE_ROOT/target/release/codelattice:release")
    fi

    # 3. Debug binary
    if [[ -x "$CODELATTICE_ROOT/target/debug/codelattice" ]]; then
        candidates+=("$CODELATTICE_ROOT/target/debug/codelattice:debug")
    fi

    # 4. Compatibility binaries
    if [[ -x "$CODELATTICE_ROOT/target/release/gitnexus-rust-core-cli" ]]; then
        candidates+=("$CODELATTICE_ROOT/target/release/gitnexus-rust-core-cli:release-compat")
    fi
    if [[ -x "$CODELATTICE_ROOT/target/debug/gitnexus-rust-core-cli" ]]; then
        candidates+=("$CODELATTICE_ROOT/target/debug/gitnexus-rust-core-cli:debug-compat")
    fi

    # Try candidates: prefer all-language binaries.
    for entry in "${candidates[@]}"; do
        local bin="${entry%%:*}"
        local profile="${entry##*:}"
        _get_profile "$bin"
        if [[ "$_PROFILE_CANGJIE" == "True" && "$_PROFILE_ARKTS" == "True" && "$_PROFILE_TYPESCRIPT" == "True" ]]; then
            SELECTED_BIN="$bin"
            SELECTED_SOURCE="$profile (all-languages=true)"
            return
        fi
    done

    # Fall back to first candidate even without all optional adapters.
    if [[ ${#candidates[@]} -gt 0 ]]; then
        local entry="${candidates[0]}"
        local bin="${entry%%:*}"
        local profile="${entry##*:}"
        SELECTED_BIN="$bin"
        _get_profile "$bin"
        SELECTED_SOURCE="$profile (cangjie=$_PROFILE_CANGJIE arkts=$_PROFILE_ARKTS typescript=$_PROFILE_TYPESCRIPT)"
        return
    fi

    # 4. No pre-built binary — cargo run fallback
    SELECTED_BIN=""
    SELECTED_SOURCE="cargo-run-fallback"
}

# --- CLI flags ---
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    cat <<'EOF'
codelattice-mcp.sh — CodeLattice Development MCP Startup Wrapper

Starts the CodeLattice MCP server from a development checkout.
The server speaks newline-delimited JSON-RPC over stdio.

Usage:
  bash scripts/codelattice-mcp.sh [options]

Options:
  --help, -h      Show this help message
  --version       Print version and profile info
  --self-test     Run diagnostic checks

Environment:
  CODELATTICE_ROOT       Source root (auto-detected from script location)
  CODELATTICE_MCP_BIN    Path to pre-built binary (skips auto-detection)
  CODELATTICE_LOG_LEVEL  Reserved for future log control

Binary selection:
  1. CODELATTICE_MCP_BIN (if set)
  2. target/release/codelattice (if exists, prefer all-language build)
  3. target/debug/codelattice (if exists, prefer all-language build)
  4. target/release/gitnexus-rust-core-cli (compat)
  5. target/debug/gitnexus-rust-core-cli (compat)
  6. cargo run --features tree-sitter-cangjie,tree-sitter-arkts,tree-sitter-typescript --bin codelattice (fallback)

Profile:
  The wrapper detects cangjieSupport, arktsSupport, and typescriptSupport from
  the binary's MCP initialize response.
  If no all-language binary is found, it warns and suggests rebuild.

Examples:
  # Default startup (from any cwd)
  bash /path/to/codelattice/scripts/codelattice-mcp.sh

  # Recommended stable runtime for ordinary AI clients
  bash /path/to/codelattice/scripts/promote-to-local-tool.sh --install-dir "$HOME/Desktop/CodeLattice-Tool"
  bash "$HOME/Desktop/CodeLattice-Tool/codelattice-mcp.sh" --self-test

  # With pre-built binary
  CODELATTICE_MCP_BIN=/usr/local/bin/codelattice \
      bash scripts/codelattice-mcp.sh

  # In MCP client config (Codex / Claude / opencode), prefer the promoted wrapper.
  # See docs/architecture/mcp-local-client-setup.md
EOF
    exit 0
fi

if [[ "${1:-}" == "--version" ]]; then
    _select_binary
    echo "codelattice-mcp-wrapper 0.7.0"
    echo "  root: $CODELATTICE_ROOT"
    if [[ -n "$SELECTED_BIN" ]]; then
        echo "  bin:  $SELECTED_BIN"
        echo "  source: $SELECTED_SOURCE"
        _get_profile "$SELECTED_BIN"
        echo "  serverVersion: $_PROFILE_VERSION"
        echo "  cangjieSupport: $_PROFILE_CANGJIE"
        echo "  arktsSupport: $_PROFILE_ARKTS"
        echo "  typescriptSupport: $_PROFILE_TYPESCRIPT"
        echo "  toolCount: $_PROFILE_TOOLS"
    else
        echo "  bin:  (cargo run fallback)"
        echo "  source: cargo-run-fallback (will build all language adapters)"
    fi
    exit 0
fi

if [[ "${1:-}" == "--self-test" ]]; then
    echo "codelattice-mcp self-test"
    echo "  root: $CODELATTICE_ROOT"

    # Check root validity
    if [[ ! -d "$CODELATTICE_ROOT" ]]; then
        echo "FAIL: CODELATTICE_ROOT does not exist: $CODELATTICE_ROOT"
        exit 1
    fi
    if [[ ! -f "$CODELATTICE_ROOT/Cargo.toml" ]]; then
        echo "FAIL: No Cargo.toml in CODELATTICE_ROOT"
        exit 1
    fi
    echo "  root: OK"

    # Check binary
    _select_binary
    if [[ -n "$SELECTED_BIN" ]]; then
        echo "  bin:  $SELECTED_BIN"
        echo "  source: $SELECTED_SOURCE"
        _get_profile "$SELECTED_BIN"
        echo "  serverVersion: $_PROFILE_VERSION"
        echo "  cangjieSupport: $_PROFILE_CANGJIE"
        echo "  arktsSupport: $_PROFILE_ARKTS"
        echo "  typescriptSupport: $_PROFILE_TYPESCRIPT"
        echo "  toolCount: $_PROFILE_TOOLS"
    else
        echo "  bin:  (cargo run fallback — no pre-built binary found)"
        echo "  hint: Run 'bash $(cd "$SCRIPT_DIR/.." && pwd)/scripts/install-mcp.sh --build'"
        # Can't do MCP checks without binary
        echo ""
        echo "Self-test incomplete (no binary)."
        exit 1
    fi

    # MCP handshake test
    echo ""
    echo "  MCP handshake test..."
    RESP=$(echo '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"self-test","version":"1.0"}}}' | "$SELECTED_BIN" mcp 2>/dev/null | head -1)
    if echo "$RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); assert d['result']['serverInfo']['name']=='codelattice'" 2>/dev/null; then
        VER=$(echo "$RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['result']['serverInfo']['version'])" 2>/dev/null || echo "unknown")
        echo "  MCP:  OK (server v$VER)"
    else
        echo "  MCP:  FAIL — unexpected response"
        exit 1
    fi

    # Extended checks
    echo ""
    echo "  Extended checks..."
    MULTI_RESP=$(printf '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"self-test","version":"1.0"}}}\n{"jsonrpc":"2.0","method":"notifications/initialized"}\n{"jsonrpc":"2.0","id":2,"method":"tools/list"}\n{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"codelattice_cache_status","arguments":{}}}\n' | "$SELECTED_BIN" mcp 2>/dev/null)

    TOOL_COUNT=$(echo "$MULTI_RESP" | python3 -c "
import json, sys
for line in sys.stdin:
    line = line.strip()
    if not line: continue
    try:
        d = json.loads(line)
        if d.get('id') == 2:
            print(len(d['result']['tools']))
            break
    except: pass
" 2>/dev/null || echo "0")
    if [[ "$TOOL_COUNT" -ge 23 ]]; then
        echo "  tools/list: OK ($TOOL_COUNT tools)"
    else
        echo "  tools/list: FAIL ($TOOL_COUNT tools, expected >= 23)"
        exit 1
    fi

     CACHE_OK=$(echo "$MULTI_RESP" | python3 -c "
import json, sys
for line in sys.stdin:
    line = line.strip()
    if not line: continue
    try:
        d = json.loads(line)
        if d.get('id') == 3:
            t = json.loads(d['result']['content'][0]['text'])
            mem = t.get('memory', {})
            print('yes' if 'maxEntries' in mem and 'totalEvictions' in mem else 'no')
            break
    except: pass
" 2>/dev/null || echo "no")
    if [[ "$CACHE_OK" == "yes" ]]; then
        echo "  cache_status: OK (has maxEntries, totalEvictions)"
    else
        echo "  cache_status: FAIL (missing fields)"
        exit 1
    fi

    # Optional language support check
    if [[ "$_PROFILE_CANGJIE" == "True" && "$_PROFILE_ARKTS" == "True" && "$_PROFILE_TYPESCRIPT" == "True" ]]; then
        echo "  languageSupport: OK (Cangjie, ArkTS, TypeScript compiled)"
    elif [[ "$_PROFILE_CANGJIE" == "False" || "$_PROFILE_ARKTS" == "False" || "$_PROFILE_TYPESCRIPT" == "False" ]]; then
        echo "  languageSupport: WARN — optional language tools may not work"
        echo "    cangjie=$_PROFILE_CANGJIE arkts=$_PROFILE_ARKTS typescript=$_PROFILE_TYPESCRIPT"
        echo "    Fix: bash $(cd "$SCRIPT_DIR/.." && pwd)/scripts/install-mcp.sh --build"
    else
        echo "  languageSupport: unknown (could not detect)"
    fi

    echo ""
    echo "Self-test passed."
    exit 0
fi

# --- Normal startup ---
if [[ ! -d "$CODELATTICE_ROOT" ]]; then
    echo "ERROR: CODELATTICE_ROOT does not exist: $CODELATTICE_ROOT" >&2
    exit 1
fi

if [[ ! -f "$CODELATTICE_ROOT/Cargo.toml" ]]; then
    echo "ERROR: No Cargo.toml in CODELATTICE_ROOT: $CODELATTICE_ROOT" >&2
    exit 1
fi

# --- Select and launch ---
_select_binary
if [[ -n "$SELECTED_BIN" ]]; then
    _get_profile "$SELECTED_BIN"
    if [[ "$_PROFILE_CANGJIE" == "False" || "$_PROFILE_ARKTS" == "False" || "$_PROFILE_TYPESCRIPT" == "False" ]]; then
        echo "[codelattice] WARNING: optional language support missing in selected binary." >&2
        echo "[codelattice] cangjie=$_PROFILE_CANGJIE arkts=$_PROFILE_ARKTS typescript=$_PROFILE_TYPESCRIPT" >&2
        echo "[codelattice] Fix: bash $(cd "$SCRIPT_DIR/.." && pwd)/scripts/install-mcp.sh --build" >&2
    fi
    exec "$SELECTED_BIN" mcp
else
    # Fallback: cargo run with all optional language adapters.
    echo "[codelattice] No pre-built binary found. Using cargo run with all language adapters..." >&2
    exec cargo run --manifest-path "$CODELATTICE_ROOT/Cargo.toml" -p gitnexus-rust-core-cli --features tree-sitter-cangjie,tree-sitter-arkts,tree-sitter-typescript --bin codelattice --quiet -- mcp
fi
